// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: thumbnails.proto

package ytthumbs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// YouTubeThumbnailServiceClient is the client API for YouTubeThumbnailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YouTubeThumbnailServiceClient interface {
	GetThumbnails(ctx context.Context, in *ThumbnailsRequest, opts ...grpc.CallOption) (*ThumbnailsResponse, error)
}

type youTubeThumbnailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYouTubeThumbnailServiceClient(cc grpc.ClientConnInterface) YouTubeThumbnailServiceClient {
	return &youTubeThumbnailServiceClient{cc}
}

func (c *youTubeThumbnailServiceClient) GetThumbnails(ctx context.Context, in *ThumbnailsRequest, opts ...grpc.CallOption) (*ThumbnailsResponse, error) {
	out := new(ThumbnailsResponse)
	err := c.cc.Invoke(ctx, "/thumbnails.YouTubeThumbnailService/GetThumbnails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YouTubeThumbnailServiceServer is the server API for YouTubeThumbnailService service.
// All implementations must embed UnimplementedYouTubeThumbnailServiceServer
// for forward compatibility
type YouTubeThumbnailServiceServer interface {
	GetThumbnails(context.Context, *ThumbnailsRequest) (*ThumbnailsResponse, error)
	mustEmbedUnimplementedYouTubeThumbnailServiceServer()
}

// UnimplementedYouTubeThumbnailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedYouTubeThumbnailServiceServer struct {
}

func (UnimplementedYouTubeThumbnailServiceServer) GetThumbnails(context.Context, *ThumbnailsRequest) (*ThumbnailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnails not implemented")
}
func (UnimplementedYouTubeThumbnailServiceServer) mustEmbedUnimplementedYouTubeThumbnailServiceServer() {
}

// UnsafeYouTubeThumbnailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YouTubeThumbnailServiceServer will
// result in compilation errors.
type UnsafeYouTubeThumbnailServiceServer interface {
	mustEmbedUnimplementedYouTubeThumbnailServiceServer()
}

func RegisterYouTubeThumbnailServiceServer(s grpc.ServiceRegistrar, srv YouTubeThumbnailServiceServer) {
	s.RegisterService(&YouTubeThumbnailService_ServiceDesc, srv)
}

func _YouTubeThumbnailService_GetThumbnails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbnailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YouTubeThumbnailServiceServer).GetThumbnails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thumbnails.YouTubeThumbnailService/GetThumbnails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YouTubeThumbnailServiceServer).GetThumbnails(ctx, req.(*ThumbnailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YouTubeThumbnailService_ServiceDesc is the grpc.ServiceDesc for YouTubeThumbnailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YouTubeThumbnailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thumbnails.YouTubeThumbnailService",
	HandlerType: (*YouTubeThumbnailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThumbnails",
			Handler:    _YouTubeThumbnailService_GetThumbnails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thumbnails.proto",
}
