name: Go CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker-compose build app

      - name: Run tests in Docker container
        run: docker-compose run --rm app go test -v ./...

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}

      - name: Push Docker image to registry
        run: docker-compose push app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -i private_key docker-compose.yml ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:/path/to/deploy
          ssh -i private_key ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'cd /path/to/deploy && docker-compose pull && docker-compose up -d'
