name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          /go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Lint code
      run: go vet ./...

    - name: Run tests
      run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1

    - name: Build
      run: go build -o myapp ./...

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        echo "${{ env.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        scp -i private_key myapp ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:/path/to/deploy
        ssh -i private_key ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'sudo systemctl restart myapp'

